export const mockProducts = [
  {
    _id: "leather-bag-001",
    title: "Classic Leather Tote",
    description: "A timeless handcrafted tote for everyday elegance.",
    price: 149,
    originalPrice: 199,
    images: [
      "/products/bag1.jpg",
      "/products/bag1.jpg",
      "/products/bag1.jpg",
    ],
    category: "Bags",
    brand: "LeatherCraft",
    model: "BAG-CL001",
    tags: ["Tote", "Luxury", "Daily Use"],
  },
  {
    _id: "leather-wallet-001",
    title: "Premium Wallet",
    description: "Slim, durable, and crafted from the finest leather.",
    price: 79,
    originalPrice: 110,
    images: [
      "/products/wallet1.jpg",
      "/products/wallet1.jpg",
      "/products/wallet1.jpg",
    ],
    category: "Wallets",
    brand: "William Polo",
    model: "WP-WL001",
    tags: ["Wallet", "Men", "Genuine Leather"],
  },
  {
    _id: "leather-belt-001",
    title: "Elegant Leather Belt",
    description: "Add sophistication to your outfit with this stylish belt.",
    price: 49,
    originalPrice: 65,
    images: [
      "/products/belt1.jpeg",
      "/products/belt1.jpeg",
      "/products/belt1.jpeg",
    ],
    category: "Belts",
    brand: "BuckleMate",
    model: "BM-BLT01",
    tags: ["Belt", "Men", "Accessories"],
  },
  {
    _id: "leather-backpack-001",
    title: "Urban Leather Backpack",
    description: "Spacious, classy, and built for modern explorers.",
    price: 199,
    originalPrice: 250,
    images: [
      "/products/bag2.webp",
      "/products/bag2.webp",
      "/products/bag2.webp",
    ],
    category: "Bags",
    brand: "TravelLux",
    model: "TL-BP01",
    tags: ["Backpack", "Office", "Travel"],
  },
  {
    _id: "leather-duffle-001",
    title: "Luxury Duffle Bag",
    description: "Perfect for weekend getaways with premium style.",
    price: 229,
    originalPrice: 280,
    images: [
      "/products/duffle1.jpg",
      "/products/duffle1.jpg",
      "/products/duffle1.jpg",
    ],
    category: "Bags",
    brand: "UrbanEdge",
    model: "UE-DF001",
    tags: ["Duffle", "Weekend", "Large"],
  },
];
